REFRESH.NET(DIAN_MAULIDA)/Applicationform/Applicationform/Controllers/ApplicantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Applicantform.Models;
using Applicationform.Repo;
using Applicationform.ViewModels;

namespace Applicationform.Controllers
{
    public class ApplicantController : Controller
    {
        // GET: Applicant
        public ActionResult Index()
        {
            List<tbl_applicant> ListApplicant = ApplicationformRepo.GetAllData();
            return View(ListApplicant);
          
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Create(tbl_applicant dataApplicant)
        {

            string result = ApplicationformRepo.CreateData(dataApplicant);
            return Json(new { respon = result }, JsonRequestBehavior.AllowGet);

        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            
            tbl_applicant  dataApplicant = ApplicationformRepo.GetDataById(Id);
            return View(dataApplicant );
        }
        [HttpPost]
        public ActionResult Edit(tbl_applicant dataApplicant)
        {

            string result = ApplicationformRepo.UpdateData(dataApplicant );
            return Json(new { respon = result }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetDataById(int Id)
        {
            tbl_applicant  data = new tbl_applicant ();
            using (applicant_dbEntities  db = new applicant_dbEntities ())
            {
                data = db.tbl_applicant.Where(a => a.Id == Id).FirstOrDefault();
            }

            return Json(new { respon = data }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult Delete(int Id)
        {
            string result = ApplicationformRepo.DeleteData(Id);
            return Json(new { respon = result }, JsonRequestBehavior.AllowGet);
        }
    }
}

REFRESH.NET(DIAN_MAULIDA)/Applicationform/Applicationform/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Applicationform.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

REFRESH.NET(DIAN_MAULIDA)/Applicationform/Applicationform/Views/Applicant/Create.cshtml
@{
    
    ViewBag.Title = "Create";
}
<style type="text/css">
    .labelfrm {
        display: block;
        font-size: small;
        margin-top: 5px;
    }

    .error {
        font-size: small;
        color: red;
    }
</style>
@using (Html.BeginForm("Create", "Applicant", FormMethod.Post, new { id = "form_create" }))
{
<br />
<br />
<div class="container" style="position:center">
    <div class="row" style="text-align:center;height:60%; width:70%;margin-left:20%;">
        <div class="col-lg-4">
            <img src="img/xsis.jpeg" style="width:40%;height:30%;" />
        </div>
        <div class="col-lg-8" style="text-align:center">
            <h1 class="text-info"><b>Welcome to PT. Xsis Mitra Utama</b></h1>
            <h4 class="text-info">

                We offers you the chance to join with us and expand your talent, skill and experience in IT industry.
            </h4>
        </div>
    </div>
    <hr />
    <div class="alert alert-info" style="text-align:center;height:60%; width:70%;margin-left:20%;">
        To apply, please fill out all the required personal information (information with red stars must strictly be filled) and then submit your form. For the next process , we will inform you by phone, sms or email (from recruitment@xsis.co.id).

    </div>
    <div class="panel panel-default" style="height:60%; width:70%; text-align:right;position:center;margin-left:20%;margin-right:10%;">
        <div class="panel-heading" style="text-align:left">Application Form</div>

        <div class="panel-body">
            <div class="row">
                <div class="col-lg-6">
                    <label for="name" class="labelfrm">Name : *</label>
                </div>
                <div class="col-lg-6">
                    <input type="text" class="form-control" id="Name" name="Name" required>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-lg-6">
                    <label for="name" class="labelfrm">Mobile Phone Number : *</label>
                </div>
                <div class="col-lg-6">
                    <input type="text" class="form-control" id="Mobile_Phone_Number" name="Mobile_Phone_Number" placeholder="0888888888" required>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-lg-6">
                    <label for="name">Alternative Phone Number : </label>
                </div>
                <div class="col-lg-6">
                    <input type="text" class="form-control" id="Alternative_Phone_Number" name="Alternative_Phone_Number">
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-lg-6">
                    <label for="name" class="labelfrm">Email : *</label>
                </div>
                <div class="col-lg-6">
                    <input type="text" class="form-control" id="Email" name="Email" required placeholder="yourEmail@yahoo.com">
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-lg-6">
                    <label for="name" class="labelfrm">Place Of Birth : *</label>
                </div>
                <div class="col-lg-6">
                    <input type="text" class="form-control" id="Place_of_Birth " name="Place_of_Birth" required>
                </div>
            </div><br />
            <div class="row">
                <div class="col-lg-6">
                    <label for="name" class="labelfrm">Date Of Birth : *</label>
                </div>
                <div class="col-lg-6">
                    <input type="date" class="form-control" id="Date_of_Birth " name="Date_of_Birth" required>
                </div>
            </div><br />
            <div class="row">
                <div class="col-lg-6">
                    <label for="name" class="labelfrm">Last Education : *</label>
                </div>
                <div class="col-lg-6">
                    @Html.DropDownList("Last_Education", new List<SelectListItem>
     { new SelectListItem { Text = "-- Choose --", Value = "", Selected=true},
       new SelectListItem { Text = "S2/S3", Value = "S2/S3"},
       new SelectListItem { Text = "S1", Value = "S1"},
        new SelectListItem { Text = "D3", Value = "D3"},
          new SelectListItem { Text = "SMU/SMK", Value = "SMU/SMK"},
       }, new { @class = "form-control labelfrm", id = "Last_Education" })
                </div>
            </div><br />
            <div class="row">
                <div class="col-lg-6">
                    <label for="name" class="labelfrm">College/University : *</label>
                </div>
                <div class="col-lg-6">
                    <input type="text" class="form-control" id="Collage_University " name="Collage_University" required>
                </div>
            </div><br />
           
            <div class="row">
                <div class="col-lg-6">
                    <label for="name" class="labelfrm">Major : *</label>
                </div>
                <div class="col-lg-6">
                    <input type="text" class="form-control" id="Major" name="Major" required>
                </div>
            </div><br />
            <div class="row">
                <div class="col-lg-6">
                    <label for="name" class="labelfrm" style="text-align:right">Position Apply : *</label>
                </div>
                <div class="col-lg-6">
                    <input type="text" class="form-control" id="Position_Apply" name="Position_Apply" required>
                </div>
            </div><br />
            <div class="row">
                <div class="col-lg-12" style="text-align:left;margin-left:20%">
                    <label for="name" class="labelfrm">How did you come to know of this vacancy ?</label>
                </div>

            </div><br />
            <div class="row">
                <div class="col-lg-6">
                    <label for="name" class="labelfrm" style="text-align:right">Source : *</label>
                </div>
                <div class=" dropdown col-lg-6" >
                    @Html.DropDownList("Source", new List<SelectListItem>
     { new SelectListItem { Text = "-- Choose --", Value = "", Selected=true},
       new SelectListItem { Text = "Event", Value = "Event"},
       new SelectListItem { Text = "Career Center", Value = "Career Center"},
        new SelectListItem { Text = "Referral Program", Value = "Referral Program"},
       }, new { @class = "form-control labelfrm", id = "Source" })
                </div>
            </div><br />
            <div class="row" style="text-align:left;margin-left:15%;">


                <button type="submit" class="cls_yes btn btn-default">Submit</button>
                <button type="button" class="cls_batal btn btn-default">Reset</button>
            </div>
        </div>
    </div>
</div>
}
<script>
    $("#form_create").validate({
        rules: {
            Name: {
                required: true
                
            },
            Mobile_Phone_Number: {
                required: true
                
               
            },
            Email: {
                required: true
                
            },
            Place_of_Birth: {
                required: true
             
            },
            Date_of_Birth: {
                required: true

            },
            Last_Education: {
                required: true

            },
            Collage_University: {
                required: true

            },
            Major: {
                required: true

            },
            Position_Apply: {
                required: true

            },
            Source: {
                required: true

            }
           
        },
        messages: {
            Name: {
                required: "Please enter your firstname"
                
            },
            Mobile_Phone_Number: {
                required: "Please enter the number only, min 10 number And max 13 number"
                
               
            },
            Email: {
                required: "Please enter a valid Email Address"

            },
            Place_of_Birth: {
                required: "Please enter a Place of Birth"

            },
            Date_of_Birth: {
                required: "Please enter a Date of Birth"

            },
            Last_Education: {
                required: "please enter your Last Education"

            },
            College_University: {
                required: "Please enter your College"

            },
            Major: {
                required: "Please enter your Major"

            },
            Position_Apply: {
                required: "Please enter a Position Apply"

            },
            Source: {
                required: "Please select Source"

            }
           

        },
        submitHandler: function (form) {
            var dataForm = $(form).serialize();
            //debugger;
            $.ajax({
                url: "@Url.Action("Create", "Applicant")",

                method: "post",
                data: dataForm,
                dataType: "json",
                success: function (respon) {
                    //debugger;
                    if (respon.respon == "Berhasil") {
                        alert("Data Berhasil Dimasukkan");
                    }
                    else {
                        alert(respon.respon);
                    }
                }
            });
        }
    });
    $(".cls_batal").click(function () {
        window.location.reload();
    });
</script>

REFRESH.NET(DIAN_MAULIDA)/Applicationform/Applicationform/Views/Applicant/Edit.cshtml
@model Applicantform.Models.tbl_applicant
@{
    ViewBag.Title = "Edit";
    Layout = null;
}
<style type="text/css">
    .labelfrm {
        display: block;
        font-size: small;
        margin-top: 5px;
    }

    .error {
        font-size: small;
        color: red;
    }
</style>
@using (Html.BeginForm("Edit", "Applicant", FormMethod.Post, new { id = "form_create" }))
{
    @Html.HiddenFor(a => a.Id);
    <form>
        <div class="panel panel-default" style="height:60%; width:70%; text-align:right;position:center;margin-left:20%;margin-right:10%;">
            <div class="panel-heading" style="text-align:left">Application Form</div>

            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6">
                        <label for="name" class="labelfrm">Name : *</label>
                    </div>
                    <div class="col-lg-6">
                        <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name" required>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-lg-6">
                        <label for="name" class="labelfrm">Mobile Phone Number : *</label>
                    </div>
                    <div class="col-lg-6">
                        <input type="text" class="form-control" id="Mobile_Phone_Number" name="Mobile Phone Number" value="@Model.Mobile_Phone_Number" placeholder="0888888888" required>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-lg-6">
                        <label for="name">Alternative Phone Number : </label>
                    </div>
                    <div class="col-lg-6">
                        <input type="text" class="form-control" id="Alternative_Phone_Number" name="Alternative_Phone_Number" value="@Model.Alternative_Phone_Number">
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-lg-6">
                        <label for="name" class="labelfrm">Email : *</label>
                    </div>
                    <div class="col-lg-6">
                        <input type="text" class="form-control" id="Email" name="Email" required placeholder="yourEmail@yahoo.com" value="@Model.Email">
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-lg-6">
                        <label for="name" class="labelfrm">Place Of Birth : *</label>
                    </div>
                    <div class="col-lg-6">
                        <input type="text" class="form-control" id="Place_of_Birth " name="Place_of_Birth" required value="@Model.Place_of_Birth">
                    </div>
                </div><br />
                <div class="row">
                    <div class="col-lg-6">
                        <label for="name" class="labelfrm">Date Of Birth : *</label>
                    </div>
                    <div class="col-lg-6">
                        <input type="date" class="form-control" id="Date_of_Birth " name="Date_of_Birth" value="@Model.Date_of_Birth" required>
                    </div>
                </div><br />
                <div class="row">
                    <div class="col-lg-6">
                        <label for="name" class="labelfrm">Last Education : *</label>
                    </div>
                    <div class="col-lg-6">
                        @Html.DropDownList("Last_Education", new List<SelectListItem>
     { new SelectListItem { Text = "-- Choose --", Value = "", Selected=true},
       new SelectListItem { Text = "S2/S3", Value = "S2/S3"},
       new SelectListItem { Text = "S1", Value = "S1"},
        new SelectListItem { Text = "D3", Value = "D3"},
          new SelectListItem { Text = "SMU/SMK", Value = "SMU/SMK"},
       }, new { @class = "form-control labelfrm", id = "Last_Education" })
                    </div>
                </div><br />
                <div class="row">
                    <div class="col-lg-6">
                        <label for="name" class="labelfrm">College/University : *</label>
                    </div>
                    <div class="col-lg-6">
                        <input type="text" class="form-control" id="College_University " name="College_University" value="@Model.Collage_University" required>
                    </div>
                </div><br />

                <div class="row">
                    <div class="col-lg-6">
                        <label for="name" class="labelfrm">Major : *</label>
                    </div>
                    <div class="col-lg-6">
                        <input type="text" class="form-control" id="Major" name="Major" value="@Model.Major" required>
                    </div>
                </div><br />
                <div class="row">
                    <div class="col-lg-6">
                        <label for="name" class="labelfrm" style="text-align:right">Position Apply : *</label>
                    </div>
                    <div class="col-lg-6">
                        <input type="text" class="form-control" id="Position_Apply" name="Position_Apply" value="@Model.Position_Apply" required>
                    </div>
                </div><br />
                <div class="row">
                    <div class="col-lg-12" style="text-align:left;margin-left:20%">
                        <label for="name" class="labelfrm">How did you come to know of this vacancy ?</label>
                    </div>

                </div><br />
                <div class="row">
                    <div class="col-lg-6">
                        <label for="name" class="labelfrm" style="text-align:right">Source : *</label>
                    </div>
                    <div class=" dropdown col-lg-6">
                        @Html.DropDownList("Source", new List<SelectListItem>
     { new SelectListItem { Text = "-- Choose --", Value = "", Selected=true},
       new SelectListItem { Text = "Event", Value = "Event"},
       new SelectListItem { Text = "Career Center", Value = "Career Center"},
        new SelectListItem { Text = "Referral Program", Value = "Referral Program"},
       }, new { @class = "form-control labelfrm", id = "Source" })
                    </div>
                </div><br />
                <div class="modal-footer">
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <button type="button" class="cls_btn_batal btn btn-warning" data-dissmiss="modal" style="background-color:deepskyblue;font-weight:bold;">Batal</button>
                        <button type="submit" class="cls_simpan btn btn-primary" style="background-color:darkblue;font-weight:bold;">Simpan</button>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </form>
}
<script>
    $("#form_create").validate({
        rules: {
            Name: {
                required: true

            },
            Mobile_Phone_Number: {
                required: true


            },
            Email: {
                required: true

            },
            Place_of_Birth: {
                required: true

            },
            Date_of_Birth: {
                required: true

            },
            Last_Education: {
                required: true

            },
            Collage_University: {
                required: true

            },
            Major: {
                required: true

            },
            Position_Apply: {
                required: true

            },
            Source: {
                required: true

            }

        },
        messages: {
            Name: {
                required: "Please enter your firstname"

            },
            Mobile_Phone_Number: {
                required: "Please enter the number only, min 10 number And max 13 number"


            },
            Email: {
                required: "Please enter a valid Email Address"

            },
            Place_of_Birth: {
                required: "Please enter a Place of Birth"

            },
            Date_of_Birth: {
                required: "Please enter a Date of Birth"

            },
            Last_Education: {
                required: "please enter your Last Education"

            },
            College_University: {
                required: "Please enter your College"

            },
            Major: {
                required: "Please enter your Major"

            },
            Position_Apply: {
                required: "Please enter a Position Apply"

            },
            Source: {
                required: "Please select Source"

            }


        },
        submitHandler: function (form) {
            var dataForm = $(form).serialize();
            //debugger;
            $.ajax({
                url: "@Url.Action("Edit", "Applicant")",

                method: "post",
                data: dataForm,
                dataType: "json",
                success: function (respon) {
                    //debugger;
                    if (respon.respon == "Berhasil") {
                        alert("Data Berhasil DiEdit");
                    }
                    else {
                        alert(respon.respon);
                    }
                }
            });
        }
    });
    $(".cls_batal").click(function () {
        $("#exampleModal3").modal("hide");
    });
</script>

REFRESH.NET(DIAN_MAULIDA)/Applicationform/Applicationform/Views/Applicant/Index.cshtml
@model  List<Applicantform.Models.tbl_applicant>
@{
    ViewBag.Title = "Index";
}

<h2>Data Application Form</h2>
<table class="table table-striped">
    <thead>
        <tr style="border-bottom: 1px solid #1c1aab">
            <th scope="col">Name</th>
            <th scope="col">Mobile_Phone_Number</th>
            <th scope="col">Email</th>
            <th scope="col">Action</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>@item.Name</td>
                <td>@item.Mobile_Phone_Number</td>
                <td>@item.Email</td>
                <td>
                    <button type="button" class="btn btn-info cls_edit" Id_applicant="@item.Id">Edit</button>
                    <button type="button" class="btn btn-danger cls_btn_delete " Id_applicant="@item.Id">Delete</button>
                </td>

            </tr>
        }
    </tbody>
</table>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" id="modal_dialog_id3">
        <div class="modal-content">
            <div class="modal-header" id="modal_header_id3">
                <h5 class="modal-title" id="exampleModalLabel3"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal_body_id3"></div>
            <div class="modal-footer" id="modal_footer_id3" style="display:none; background-color:darkgrey;">
                <div class="btn-group" role="group" aria-label="Basic example">
                    <button type="button" class="btn btn-warning" data-dismiss="modal" style="background-color:darkorange;font-weight:bold;">Tidak</button>
                    <button type="button" class="btn btn-danger cls_delete" style="background-color:darkred;font-weight:bold;">Ya</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(".cls_btn_delete").click(function () {
        var Id = $(this).attr("Id_applicant");
        var data = "";
        debugger;
        $.ajax({
            url: "@Url.Action("GetDataById", "Applicant")",
            method: "get",
            dataType: "json",
            data: { Id: Id },
            success: function (respon) {
                //debugger;
                data = respon;
                $("#modal_body_id3").empty();
                $("#exampleModalLabel3").empty();
                $("#modal_body_id3").empty();
                $("#modal_dialog_id3").css({ 'width': '45%' });
                //$("#modal_dialog_id1").css({ 'padding-bottom': '20%' });
                $("#modal_body_id3").css({ 'padding-bottom': '20%' });
                $("#modal_footer_id3").show();
                $("#modal_header_id3").css({ 'background-color': 'darkred' });
                $("#modal_footer_id3").css({ 'background-color': 'white' });
                $("#exampleModalLabel3").append("Hapus Application Form");

                $("#modal_body_id3").html("<div class='row'><div class ='col-lg-2'style='color:black'><span class='glyphicon glyphicon-trash' style='font-size:60px'></span></div><div class='col-lg-10' style='padding-top:8%;color:darkred;'>Anda Yakin ingin menghapus Application Form  " + data.respon.Name + "</div></div>");
                $("#exampleModal").modal("show");

                $(".cls_delete").click(function () {
                    debugger;
                    $.ajax({
                        url: "@Url.Action("Delete","Applicant")",
                        method: "get",
                        data: { Id: Id },
                        success: function (respon) {
                            //debugger;
                            if (respon.respon == "Berhasil") {
                                window.location.reload();
                                alert("Data berhasil dihapus");
                            }
                            else {
                                alert(respon.respon);
                            }
                        }
                    })
                })
            }
        })
    });

    $(".cls_edit").click(function () {
        debugger;
        var Id = $(this).attr("Id_applicant");

        $.ajax({
            url: "@Url.Action("Edit","Applicant")",
            method: "get",
            data: { Id: Id },
            success: function (respon) {
                $("#modal_body_id3").empty();
                $("#exampleModalLabel3").empty();
                $("#modal_dialog_id3").css({ 'width': '80%' });
                $("#modal_header_id3").css({ 'background-color': 'darkblue' });
                $("#exampleModalLabel3").append("Ubah Organisasi");
                $("#modal_body_id3").append(respon);
                $("#exampleModal3").modal("show");
                $("#modal_footer_id3").hide();
            }
        });
    });
</script>

REFRESH.NET(DIAN_MAULIDA)/Applicationform/Applicationform/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

REFRESH.NET(DIAN_MAULIDA)/Applicationform/Applicationform/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

REFRESH.NET(DIAN_MAULIDA)/Applicationform/Applicationform/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

REFRESH.NET(DIAN_MAULIDA)/Applicationform/Applicationform/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Applicant", "Create", "Applicant")</li>
                    <li>@Html.ActionLink("Data Applicant", "Index", "Applicant")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>